# travis-ci does not have first-class support for octave
language: generic

addons:
  apt:
    sources:
    - sourceline: 'ppa:octave/stable'
    packages:
    - octave

script:
    - octave-cli tests/run_tests.m